services:
  server:
    image: ghcr.io/hututuono/mediaunlock-server:latest
    container_name: mediaunlock
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /opt/mediaunlock/config.yml:/app/config.yml
      - /opt/mediaunlock/data:/app/data